---
# Codacy configuration for VueJS Tour project
engines:
  # ESLint for JavaScript/TypeScript/Vue linting
  eslint:
    enabled: true
    exclude_paths:
      - 'vite.config.*'
      - 'vitest.config.*'
      - '*.d.ts'
      - 'env.d.ts'
      - 'docs/.vitepress/**'
    configuration:
      rules:
        # Allow unused parameters in interface method signatures (public API definitions)
        "@typescript-eslint/no-unused-vars":
          - "error"
          - "argsIgnorePattern": "^(stepIndex|shouldRestart)$"
            "varsIgnorePattern": "^_"
            "args": "after-used"
    
  # TypeScript linting
  typescript:
    enabled: true
    exclude_paths:
      - '*.d.ts'
      - 'env.d.ts'
      - 'vite.config.*'
      - 'vitest.config.*'
      
  # Duplication detection
  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'
      - 'docs/**'
      - 'coverage/**'
      
  # Code complexity analysis
  metrics:
    enabled: true
    exclude_paths:
      - 'test/**'
      - 'docs/**'
      - 'coverage/**'
      - 'vite.config.*'
      - 'vitest.config.*'
      
  # CSS/SCSS linting
  csslint:
    enabled: true
    exclude_paths:
      - 'coverage/**'
      - 'docs/**'

# Global exclude patterns
exclude_patterns:
  # Dependencies and build artifacts
  - 'node_modules/**'
  - 'dist/**'
  - 'coverage/**'
  - '.vitepress/cache/**'
  
  # Test files (if you want to exclude from analysis)
  - 'test/**'
  
  # Configuration files that don't need deep analysis
  - '*.config.*'
  - '*.d.ts'
  - 'env.d.ts'
  - 'tsconfig*.json'
  
  # Documentation build artifacts
  - 'docs/.vitepress/dist/**'
  
  # Generated files
  - '*.tsbuildinfo'
  - '*.gif'
  - '*.png'
  - '*.jpg'
  - '*.jpeg'
  - '*.svg'
  - '*.ico'
  
  # Package files
  - '*.tgz'
  - '*.tar.gz'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'pnpm-lock.yaml'
  
  # IDE and editor files
  - '.vscode/**'
  - '.idea/**'
  - '*.swp'
  - '*.swo'
  - '*~'
  
  # OS generated files
  - '.DS_Store'
  - 'Thumbs.db'

# File size limits (optional)
file_size_limit: 5000  # Lines

# Complexity thresholds (optional)
complexity_threshold: 15
